### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by GDI-ZOCOM** [VazkiiMods/Bliss#108]
[16:32:08] [main/ERROR]: Mixin config minetogether.mixins.json does not specify "minVersion" property
[16:32:11] [main/ERROR]: Mixin config mixins.oculus.compat.sodium.json does not specify "minVersion" property
[16:32:12] [main/ERROR]: Mixin config polylib.mixins.json does not specify "minVersion" property
[16:32:12] [main/ERROR]: Mixin config projectsavethepets.accessors.mixins.json does not specify "minVersion" property
[16:32:13] [main/ERROR]: Mixin config projectsavethepets.mixins.json does not specify "minVersion" property
[16:32:13] [main/ERROR]: Mixin config radium.mixins.json does not specify "minVersion" property
[16:32:14] [main/ERROR]: Mixin config rubidium.mixins.json does not specify "minVersion" property
[16:32:50] [main/INFO]: Successfully loaded Mixin Connector [tictim.paraglider.MixinConnector]
[16:32:51] [main/INFO]: Successfully loaded Mixin Connector [ca.spottedleaf.starlight.mixin.MixinConnector]
[16:32:51] [main/INFO]: Successfully loaded Mixin Connector [org.tlauncher.MixinConnector]
[16:32:53] [main/INFO]: Launching target 'forgeclient' with arguments [--version, Zone ops, --gameDir, C:\Users\student\AppData\Roaming\.minecraft\versions\Zone ops, --assetsDir, C:\Users\student\AppData\Roaming\.minecraft\assets, --uuid, ac0f578bc0c04022b3323ee826faffa3, --username, GDI_ZOCOM, --assetIndex, 1.18, --accessToken, ????????, --clientId, ${clientid}, --xuid, ${auth_xuid}, --userType, mojang, --versionType, release, --width, 925, --height, 530]
[16:32:62] [main/WARN]: Reference map 'farmersrespite.refmap.json' for farmersrespite.mixins.json could not be read. If this is a development environment you can ignore this message
[16:32:69] [main/WARN]: Reference map 'musictriggers.refmap.json' for musictriggers.mixin.json could not be read. If this is a development environment you can ignore this message
[16:32:72] [main/WARN]: Reference map 'overweightfarming.refmap.json' for overweightfarming.mixins.json could not be read. If this is a development environment you can ignore this message
[16:32:72] [main/WARN]: Reference map 'polylib-common-refmap.json' for polylib.mixins.json could not be read. If this is a development environment you can ignore this message
[16:32:76] [main/INFO]: Loaded configuration file for Radium: 100 options available, 0 override(s) found
[16:32:78] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[16:32:78] [main/INFO]: Loaded configuration file for Rubidium: 29 options available, 0 override(s) found
[16:32:86] [main/WARN]: Reference map 'yungsbridges.refmap.json' for yungsbridges.mixins.json could not be read. If this is a development environment you can ignore this message
[16:32:86] [main/WARN]: Reference map 'yungsbridges.refmap.json' for yungsbridges_forge.mixins.json could not be read. If this is a development environment you can ignore this message
[16:32:87] [main/WARN]: Reference map 'yungsextras.refmap.json' for yungsextras.mixins.json could not be read. If this is a development environment you can ignore this message
[16:32:87] [main/WARN]: Reference map 'yungsextras.refmap.json' for yungsextras_forge.mixins.json could not be read. If this is a development environment you can ignore this message
[16:33:14] [main/INFO]: APPLYING MIXIN: de.keksuccino.auudio.mixin.client.MixinSoundBufferLibrary | TO TARGET: net.minecraft.client.sounds.SoundBufferLibrary
[16:33:14] [main/INFO]: APPLYING MIXIN: de.keksuccino.auudio.mixin.client.MixinSoundEngine | TO TARGET: net.minecraft.client.sounds.SoundEngine
[16:33:50] [main/WARN]: Error loading class: snownee/snow/WorldTickHandler (java.lang.ClassNotFoundException: snownee.snow.WorldTickHandler)
[16:33:31] [main/WARN]: Error loading class: snownee/snow/WorldTickHandler (java.lang.ClassNotFoundException: snownee.snow.WorldTickHandler)
[16:33:32] [main/WARN]: Error loading class: snownee/snow/WorldTickHandler (java.lang.ClassNotFoundException: snownee.snow.WorldTickHandler)
Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.run(Launcher.java:106)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.0.0/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.18.2-40.1.25/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
	... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:110)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.lambda$findClass$16(ModuleClassLoader.java:216)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:226)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:216)
	at cpw.mods.securejarhandler@1.0.3/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at TRANSFORMER/patchouli@1.18.2-67/vazkii.patchouli.client.handler.BookCrashHandler.appendToCrashReport(BookCrashHandler.java:23)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.SystemReport.handler$zne000$patchouli_addContext(SystemReport.java:1016)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.SystemReport.<init>(SystemReport.java:57)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.CrashReport.<init>(CrashReport.java:29)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.CrashReport.m_127529_(CrashReport.java:213)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.main(Main.java:137)
	... 13 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector attack(Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/entity/Entity;)D in projectsavethepets.mixins.json:PlayerEntityMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap projectsavethepets-common-refmap.json
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1362)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1051)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 32 more
Here I am!
[VersionManager] Refreshing versions locally...
[VersionManager] Versions has been refreshed (32 ms)
[Version:fabric-loader-0.12.5-1.16.5] Resolving...
[Version:fabric-loader-0.12.5-1.16.5] Inherits from 1.16.5
[Version:fabric-loader-0.12.5-1.16.5] Resolving...
[Version:fabric-loader-0.12.5-1.16.5] Inherits from 1.16.5
[Version:fabric-loader-0.12.5-1.16.5] Resolving...
[Version:fabric-loader-0.12.5-1.16.5] Inherits from 1.16.5
[Launcher] Launcher exited.
[Launcher] Minecraft closed with exit code: 1

**Comment by GDI-ZOCOM** [comment]
This is all I have. there is no crash report, just the console.

**Comment by gamingoninsulin** [comment]
I see here in the console.log

Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector attack(Lnet/minecraft/world/entity/player/Player;Lnet/minecraft/world/entity/Entity;)D 
in projectsavethepets.mixins.json:PlayerEntityMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap projectsavethepets-common-refmap.json

Try disable project save the pets and see if this helps becuase an entiy of that mod failed to load
